# Тестовое устройство типа door для проверки occupancy-логики
binary_sensor:
  - platform: template
    sensors:
      test_door:
        friendly_name: "Test Door"
        device_class: door
        value_template: "{{ is_state('input_boolean.test_door', 'on') }}"
      test_door_no_device:
        friendly_name: "Test Door No Device"
        device_class: door
        value_template: "{{ is_state('input_boolean.test_door_no_device', 'on') }}"

input_boolean:
  test_door:
    name: Test Door
    initial: off
    icon: mdi:door
  test_door_no_device:
    name: Test Door No Device
    initial: off
    icon: mdi:door 